apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: study-harbour
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  ingressClassName: nginx
  tls:
    - hosts: [study.example.org]
      secretName: study-harbour-tls
  rules:
    - host: study.example.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: study-harbour-api, port: { name: http } }

